updated post_build

diff --git a/ubuntu-github/hooks/post_build b/ubuntu-github/hooks/post_build
--- a/ubuntu-github/hooks/post_build
+++ b/ubuntu-github/hooks/post_build
@@ -17,17 +17,6 @@ set -eu
 [ -n "${DEBUG:-}" ] && set -x
 srcdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-if [ -z "${IMAGE_NAME:-}" ]; then
-    echo "IMAGE_NAME not set, determining from Makefile"
-    IMAGE_NAME="$(awk -F= '/^[[:space:]]*REPO[[:space:]]*:*=/{print $2}' "$srcdir/../Makefile" | sed 's/[[:space:]]//g;s/"//g')"
-    if [ -z "$IMAGE_NAME" ]; then
-        echo "FAILED to determine IMAGE_NAME From Makefile"
-        exit 1
-    fi
-    echo "determined image name from Makefile to be '$IMAGE_NAME'"
-fi
-DOCKER_REPO="${DOCKER_REPO:-${IMAGE_NAME/:*}}"
-
 if [ "${SOURCE_BRANCH:-}" != master ]; then
     echo "SOURCE_BRANCH not set, determining from Makefile"
     SOURCE_BRANCH="$(git branch  | sed -n 's/*[[:space:]]*//p')"
@@ -39,9 +28,25 @@ if [ "$SOURCE_BRANCH" != master ]; then
     exit 0
 fi
 
-new_tag="${IMAGE_NAME//github}"
-new_tag="${new_tag//-}"
-new_tag="${new_tag/\///github:}"
+if [ -z "${IMAGE_NAME:-}" ]; then
+    echo "IMAGE_NAME not set, determining from Makefile"
+    IMAGE_NAME="$(awk -F= '/^[[:space:]]*REPO[[:space:]]*:*=/{print $2}' "$srcdir/../Makefile" | sed 's/[[:space:]]//g;s/"//g')"
+    if [ -z "$IMAGE_NAME" ]; then
+        echo "FAILED to determine IMAGE_NAME From Makefile"
+        exit 1
+    fi
+    echo "determined image name from Makefile to be '$IMAGE_NAME'"
+fi
+
+DOCKER_REPO="${DOCKER_REPO:-${IMAGE_NAME/:*}}"
+
+if [ "$DOCKER_REPO" = "harisekhon/github" ]; then
+    new_tag="$(sed 's/\/github:\(.*\)/\/\1-github/' <<< "$IMAGE_NAME")"
+else
+    new_tag="${IMAGE_NAME//github}"
+    new_tag="${new_tag//-}"
+    new_tag="${new_tag/\///github:}"
+fi
 
 set -x
 docker tag "$IMAGE_NAME" "$new_tag"
