updated hooks for new makefile format

diff --git a/jython/hooks/post_build b/jython/hooks/post_build
--- a/jython/hooks/post_build
+++ b/jython/hooks/post_build
@@ -22,7 +22,11 @@ highest_tag="unknown"
 current_scala="2.11"
 
 if [ -z "${IMAGE_NAME:-}" ]; then
-    IMAGE_NAME="$(awk -F= '/^REPO=/{print $2}' "$srcdir/../Makefile")"
+    IMAGE_NAME="$(awk -F= '/^[[:space:]]*REPO[[:space:]]*:*=/{gsub (" ", "", $2); print $2}' "$srcdir/../Makefile")"
+    if [ -z "$IMAGE_NAME" ]; then
+        echo "FAILED to determine IMAGE_NAME From Makefile"
+        exit 1
+    fi
     echo "IMAGE_NAME not set, determined from Makefile to be '$IMAGE_NAME'"
 fi
 DOCKER_REPO="${DOCKER_REPO:-${IMAGE_NAME/:*}}"
